routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//redireccionar siempre ala ruta index 
Route::get('/', function () {
     return redirect('telefono');
});
//recurso de rutas CRUD
Route::resource('telefono', 'telefonoController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/telefono.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class telefono extends Model
{
    protected $table = 'telefonos';


    protected $fillable = [
        'id',
        'nombre',
        'direccion',
        'tipoTel',
        'telefono'
    ];

    public $timestamps = false;
    

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/telefonoController.php
<?php

namespace App\Http\Controllers;

use App\telefono;
use Illuminate\Http\Request;

class telefonoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $telefonos = telefono::all();
        return view('consultar')->with('telefono', $telefonos);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('insertar');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $telefono = new telefono;
        $telefono->nombre = $request->nombre;
        $telefono->direccion = $request->direccion;
        $telefono->tipoTel = $request->tipoTel;
        $telefono->telefono = $request->telefono;
        $telefono->save();
        return  redirect('/telefono');    
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\telefono  $telefono
     * @return \Illuminate\Http\Response
     */
    public function show(telefono $telefono)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\telefono  $telefono
     * @return \Illuminate\Http\Response
     */
    public function edit(telefono $telefono)
    {
        return view('editar')->with('telefono', $telefono);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\telefono  $telefono
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, telefono $telefono)
    {
        $telefono = telefono::where('id',$telefono->id)->firstOrFail();
        $telefono->nombre = $request->nombre;
        $telefono->direccion = $request->direccion;
        $telefono->tipoTel = $request->tipoTel;
        $telefono->telefono = $request->telefono;
        $telefono->save();
        return  redirect('/telefono');    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\telefono  $telefono
     * @return \Illuminate\Http\Response
     */
    public function destroy(telefono $telefono)
    {
        $telefono->delete();
        return  redirect('/telefono');    
    }
}

resources/views/consultar.blade.php
@extends('layout')
@section('content')
  
<a href="{{ route('telefono.create') }}" class="btn btn-primary m-2">Nueva</a>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">NOMBRE</th>
      <th scope="col">DIRECCION</th>
      <th scope="col">TIPO</th>
      <th scope="col">TELEFONO</th>
      <th scope="col">ELIMINAR</th>
      <th scope="col">ACTUALIZAR</th>
    </tr>
  </thead>
  <tbody>
  @foreach($telefono as $tel)
    <tr>
      <th scope="row">{{$tel->id}}</th>
      <td scope="row">{{$tel->nombre}}</td>
      <td scope="row">{{$tel->direccion}}</td>
      <td scope="row">{{$tel->tipoTel}}</td>
      <td scope="row">{{ $tel->telefono }}</td>
      <td scope="row">
      <form method="POST" action="{{ url("telefono/{$tel->id}") }}" >
            @csrf
            @method('DELETE')
            <button type="submit" class="btn btn-danger">Eliminar</button>
        </form>
      </td>
      <td scope="row">
        <a href="{{ url("telefono/{$tel->id}/edit") }}" class="btn btn-primary m-2">Editar</a>
      </td>
    </tr>
    @endforeach

  </tbody>
</table>


@endsection

resources/views/editar.blade.php
@extends('layout')
@section('content')

<div class="container">
<h1>Editar</h1>
<form method="POST" action="{{ url("telefono/{$telefono->id}") }}">
    @csrf   
    @method('PUT')

  <div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" value="{{ $telefono->nombre }}" class="form-control" id="nombre" name="nombre">
  </div>
  <div class="form-group">
    <label for="direccion">Dirección</label>
    <input type="text" value="{{ $telefono->direccion }}" class="form-control" id="direccion" name="direccion">
  </div>
  <div class="form-group">
    <label for="direccion">Tipo de telefono</label>
    <input type="text" value="{{ $telefono->tipoTel }}" class="form-control" id="tipoTel" name="tipoTel">
  </div>

  <div class="form-group">
    <label for="direccion">Telefono</label>
    <input type="text" value="{{ $telefono->telefono }}" class="form-control" id="telefono" name="telefono">
  </div>
  <button type="submit" class="btn btn-primary">Editar</button>

</form>
</div>

@endsection

resources/views/insertar.blade.php
@extends('layout')
@section('content')

<div class="container">
<h1>Nuevo</h1>

<form method="POST" action="/telefono">
@csrf   
  <div class="form-group">
    <label for="nombre">Nombre</label>
    <input type="text" class="form-control" id="nombre" name="nombre">
  </div>
  <div class="form-group">
    <label for="direccion">Dirección</label>
    <input type="text" class="form-control" id="direccion" name="direccion">
  </div>
  <div class="form-group">
    <label for="direccion">Tipo de telefono</label>
    <input type="text" class="form-control" id="tipoTel" name="tipoTel">
  </div>

  <div class="form-group">
    <label for="direccion">Telefono</label>
    <input type="text" class="form-control" id="telefono" name="telefono">
  </div>
 
  <button type="submit" class="btn btn-primary">Guardar</button>
</form>
</div>

@endsection

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{{ mix('css/app.css') }}" rel="stylesheet" type="text/css" />

    <title>Agenda</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <a class="navbar-brand" href="#">Mi agenda personal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
</nav>


<div class="container-fluid">
    @yield('content')
</div>

<script src="{{ mix('js/app.js') }}" type="text/javascript"></script>

</body>
</html>